### ISSUE TITLE
deconsoler can't work in a split pane

### ISSUE THREAD

**Issue by zhangDand** [vishysank/console-log-atom#18] opened 2016-11-14 13:41 UTC
somtimes , the file in the split pane, deconsoler can't find the 'console' line .
 it just log 0 rows have been removed

**Comment by vishysank** [comment] 2016-11-14 16:34
@zhangDand can you add a gif in here of this behaviour in action so that i can see exactly what the issue is ?

**Comment by vishysank** [comment] 2017-02-22 17:12
@zhangDand closing this issue due to lack to explanation and follow up. Do open it back up if you have more information.

**Closed as completed** 2017-02-22 17:12 UTC
