### ISSUE TITLE
Add option to disable context menus

### ISSUE THREAD

**Issue by camjackson** [vishysank/console-log-atom#19] opened 2016-12-09 03:18 UTC
I love the functionality of this plugin, but I only use the keyboard shortcuts. I find that the Right-Click context menus just clutter things up, so I'd like to be able to disable them.

How much work would it be to add an option for this?

**Comment by vishysank** [comment] 2016-12-12 16:38
@camjackson thats a good suggestion, i'll investigate adding a config option for this.

**Comment by pdonias** [comment] 2016-12-14 21:46
@vishysank Hi!
I implemented a quick fix for this. If you give me the permissions, I'll push it and create a pull request.

**Comment by vishysank** [comment] 2016-12-14 21:49
@pdonias that is awesome! Thanks ! I'm not sure how I can give you permissions on atom, but if push a branch to this repo and open a PR, I can review and approve it. When new code is added to master, a new atom version is automatically pushed out.

**Comment by vishysank** [comment] 2016-12-14 21:50
@pdonias, I'll also add a thank you mention in the documentation, and you'll be included as a contributer on this repo

**Comment by pdonias** [comment] 2016-12-14 21:52
The problem is I can't seem to be able to push a new branch. (`Permission to vishysank/console-log-atom.git denied to pdonias.`)
But if you go to Settings > Collaborators, you should be able to add me as a collaborator.

**Comment by vishysank** [comment] 2016-12-14 21:55
@pdonias okay, added you as a collaborator

**Comment by pdonias** [comment] 2016-12-14 21:56
Thanks :)

**Closed as completed** 2016-12-14 22:01 UTC
Labels: enhancement

**Comment by vishysank** [comment] 2016-12-14 22:13
@camjackson, as of v 1.8.0 this should now be a config option, thanks to some sweet work by @pdonias. If you guys like using the site, star it on atom or github !

**Comment by camjackson** [comment] 2016-12-17 07:17
Wow, that was quick!

@pdonias, for future reference, usually people would fork the repo into their own github account, and push it to there. Then you can create a pull request from your fork to the main repo :)

**Comment by pdonias** [comment] 2016-12-17 10:50
@camjackson copy that, thanks.
